before_install:
  - sudo apt-get -qq update
  - sudo apt-get remove -y docker docker-engine docker.io
  - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -qq update
  - sudo apt-get install -y docker-ce
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs

script:
- IP=`ip addr show | grep -i eth0 | grep -i inet | cut -d ' ' -f 6 | cut -d '/' -f1`
- cp config-example.json config.json
- sed -i "s/127.0.0.1/$IP/" config.json
- sed -i "s/192.168.0.116/$IP/" pictl
- cp -r ./example/x86_64/ubuntu/* ./docker/
- sudo docker image build ./docker/nginx -t nginx -f ./docker/nginx/Dockerfile
- sudo docker image build ./docker/minio -t minio -f ./docker/minio/Dockerfile
- sudo docker image build . -t local/testing:alpine -f web/tests/integration/Dockerfile.alpine
- sudo docker container run -d --name nginx -p 80:80 nginx
- sudo docker container run -d --name minio -p 9000:9000 minio
- cd server;npm install --production; sudo node server.js&
- cd ../agent;npm install --production; sudo node agent.js&
- cd ../web;npm install --production; sudo node webconsole.js&
- cd ..
- sudo docker run -it --rm -v "$PWD:$PWD" -w "$PWD/web/tests/integration" -e URL=http://$IP:3003 -e FONTLINUX=fl-ubuntu-inverse local/testing:alpine
- chmod +x ./pictl
- ./pictl exec "uname -a"
- ./pictl nodes
- ./pictl reloadconfig
