version: '3'
services:

  server:
    image: "node:alpine"
    restart: "always"
    volumes:
      - .:/picluster
      - ./docker-compose.config.json:/picluster/config.json
    networks:
      picluster:
        ipv4_address: 10.10.10.1
    extra_hosts:
      server: 10.10.10.1
      agent: 10.10.10.2
      docker0: 172.17.0.1
    ports:
      - "3000:3000"
    working_dir: /picluster/server
    command: ["sh", "-c", "set -e;apk add --no-cache sudo;sudo -u node npm install --production;sudo -u node node server.js;"]
  agent:
    image: "node:alpine"
    restart: "always"
    volumes:
      - .:/picluster
      - ./docker-compose.config.json:/picluster/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      picluster:
        ipv4_address: 10.10.10.2
    extra_hosts:
      server: 10.10.10.1
      agent: 10.10.10.2
      docker0: 172.17.0.1
    ports:
      - "3001:3001"
    working_dir: /picluster/agent
    command: ["sh", "-c", "set -e;apk update;apk upgrade;apk add sudo git python make g++ docker procps;export PATH=/bin:$PATH;sudo -u node npm install --production;node agent.js"]

  webconsole:
    image: "node:alpine"
    restart: "always"
    networks:
      picluster:
        ipv4_address: 10.10.10.3
    extra_hosts:
      server: 10.10.10.1
      agent: 10.10.10.2
      docker0: 172.17.0.1
    volumes:
      - .:/picluster
      - ./docker-compose.config.json:/picluster/config.json
    ports:
      - "3003:3003"
    working_dir: /picluster/web
    command: ["sh", "-c", "set -e;apk update;apk upgrade;apk add git sudo;sudo -u node npm install --production;sudo -u node node webconsole.js;"]

networks:
  picluster:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/16
