version: '2'
services:
  server:
    image: "node:alpine"
    volumes:
      - .:/picluster
      - ./docker-compose.config.json:/picluster/config.json
    ports:
      - "3000:3000"
    working_dir: /picluster/server
    command: ["sh", "-c", "npm install --production;node server.js;"]
    links:
      - agent
  agent:
    image: "node:alpine"
    volumes:
      - .:/picluster
      - ./docker-compose.config.json:/picluster/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    working_dir: /picluster/agent
    command: ["sh", "-c", "apk update;apk upgrade;apk add docker;npm install --production;node agent.js"]
  webconsole:
    image: "node:alpine"
    volumes:
      - .:/picluster
      - ./docker-compose.config.json:/picluster/config.json
    ports:
      - "3003:3003"
    working_dir: /picluster/web
    command: ["sh", "-c", "npm install --production;node webconsole.js;"]
    links:
      - server
